# Generated by Django 5.0.6 on 2024-07-05 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Hyderabad', 'Hyderabad'), ('Bangalore', 'Bangalore'), ('Mumbai', 'Mumbai'), ('Jaipur', 'Jaipur'), ('Chennai', 'Chennai'), ('Kolkata', 'Kolkata'), ('Lucknow', 'Lucknow'), ('Bhopal', 'Bhopal'), ('Chandigarh', 'Chandigarh'), ('Raipur', 'Raipur')], max_length=50, unique=True)),
                ('number_of_rooms', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Premium', 'Premium'), ('Deluxe', 'Deluxe'), ('Basic', 'Basic')], max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HBSApp.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Hyderabad', 'Hyderabad'), ('Bangalore', 'Bangalore'), ('Mumbai', 'Mumbai'), ('Jaipur', 'Jaipur'), ('Chennai', 'Chennai'), ('Kolkata', 'Kolkata'), ('Lucknow', 'Lucknow'), ('Bhopal', 'Bhopal'), ('Chandigarh', 'Chandigarh'), ('Raipur', 'Raipur')], max_length=50)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('number_of_people', models.PositiveIntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HBSApp.room')),
            ],
        ),
    ]
